# --- Docker Compose 文件版本 ---
# '3.8' 是一个稳定且功能丰富的版本。
version: '3.8'

# --- 服务定义 ---
# 在这里定义您的应用服务。
services:
  # 服务名称，可以自定义，这里我们叫它 appbot。
  appbot:
    # --- 镜像构建 ---
    # build: . 指示 Docker Compose 在当前目录下查找 Dockerfile 并构建镜像。
    # 在本地开发时，这非常方便。
    #build: .
    
    # 当您想从 Docker Hub 拉取预构建的镜像（例如，由 GitHub Actions 构建的）来运行时，
    # 可以注释掉上面的 `build: .`，然后使用下面的 `image` 指令。
    # 请将 'your-dockerhub-username/appbot:latest' 替换为您自己的镜像地址。
    image: domomido/appbot:latest

    # --- 容器配置 ---
    # 给容器一个固定的名字，方便管理。
    container_name: appbot
    # 设置重启策略为 "always"，这样容器在意外退出时会自动重启。
    restart: always
    
    # --- 环境变量 ---
    # 从项目根目录下的 .env 文件中加载环境变量。
    # 这是您要求的核心功能之一。
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
      
    # --- 端口映射 ---
    # 将主机的 8443 端口映射到容器的 8443 端口。
    # 格式是 "主机端口:容器端口"。
    ports:
      - "8443:8443"
      
    # --- 卷（目录）映射 ---
    # 将当前目录（.）挂载到容器内的 /app 目录。
    # 这意味着您在本地对代码的任何修改，都会立即反映在运行的容器中，
    # 无需重新构建镜像，极大地提高了开发效率。
    volumes:
      - .:/app
