# 工作流程名称
name: Docker Image CI

# 触发条件
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

# 定义一个 job
jobs:
  build-and-push:
    # 运行在最新的 ubuntu 系统上
    runs-on: ubuntu-latest
    # 授予 job 的权限
    permissions:
      contents: read
      packages: write

    # job 的执行步骤
    steps:
      # 第一步：拉取代码
      - name: Check out the repo
        uses: actions/checkout@v4

      # 第二步：提取版本号，并判断是否为正式发布
      - name: Extract version and release status
        id: extract_version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
            echo "IS_RELEASE=true" >> $GITHUB_ENV
          else
            VERSION="dev-$(date +'%Y%m%d-%H%M%S')"
            echo "IS_RELEASE=false" >> $GITHUB_ENV
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Version is: $VERSION"

      # 第三步：设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          # ✨ 注意：如果你的项目需要，请改成你自己的 Python 版本
          python-version: '3.10' 
      
      # 第四步：安装 Python 依赖
      - name: Install Python dependencies
        run: |
          python -m
